"""Verification, calibration, and assurance substrate."""

from dnc.assurance.contracts import (
    VerificationStatus,
    Verifier,
    VerifierClaim,
    VerifierDescriptor,
    VerifierKind,
    VerifierResult,
)
from dnc.assurance.registry import CascadePolicy, CascadeResult, VerifierCascade, VerifierRegistry
from dnc.assurance.calibration import (
    AssuranceCalibrationRegistry,
    CalibrationArtifact,
    CalibrationKey,
    CalibrationMetrics,
    CalibrationStatus,
    bootstrap_interval,
    conformal_error_bound,
    evaluate_calibration,
    fit_isotonic,
    fit_logistic,
    fit_temperature,
    population_shift,
    subgroup_analysis,
)
from dnc.assurance.outcomes import OutcomeLabel, OutcomeLabelStatus, OutcomeLabelStore
from dnc.assurance.policy import (
    RiskPolicyRegistry,
    RiskThresholdPolicy,
    calibrated_lower_bound,
    issue_confidence,
)
from dnc.assurance.semantic import (
    Contradiction,
    SemanticAttempt,
    SemanticCluster,
    cluster_attempts,
    detect_contradictions,
)
from dnc.assurance.verifiers import (
    CallbackVerifierAdapter,
    FunctionalVerifier,
    arithmetic_check,
    callable_check,
    code_test_check,
    format_check,
    provenance_check,
    policy_check,
    schema_check,
)

__all__ = [
    "CascadePolicy",
    "CascadeResult",
    "CallbackVerifierAdapter",
    "AssuranceCalibrationRegistry",
    "CalibrationArtifact",
    "CalibrationKey",
    "CalibrationMetrics",
    "CalibrationStatus",
    "Contradiction",
    "FunctionalVerifier",
    "OutcomeLabel",
    "OutcomeLabelStatus",
    "OutcomeLabelStore",
    "RiskPolicyRegistry",
    "RiskThresholdPolicy",
    "SemanticAttempt",
    "SemanticCluster",
    "VerificationStatus",
    "Verifier",
    "VerifierCascade",
    "VerifierClaim",
    "VerifierDescriptor",
    "VerifierKind",
    "VerifierRegistry",
    "VerifierResult",
    "arithmetic_check",
    "bootstrap_interval",
    "calibrated_lower_bound",
    "callable_check",
    "code_test_check",
    "cluster_attempts",
    "conformal_error_bound",
    "detect_contradictions",
    "evaluate_calibration",
    "fit_isotonic",
    "fit_logistic",
    "fit_temperature",
    "format_check",
    "issue_confidence",
    "population_shift",
    "policy_check",
    "provenance_check",
    "schema_check",
    "subgroup_analysis",
]
