"""Cognitive-runtime contracts for the expanded DNC profile."""

from dnc.cognition.calibration import (
    CalibrationProfile,
    CalibrationRegistry,
    default_reference_calibration,
)
from dnc.cognition.contracts import (
    ActionLifecycleState,
    ActionOutcome,
    ClarificationRequest,
    ClarificationStatus,
    CognitiveBudgets,
    CognitiveActionType,
    CognitiveDecision,
    CognitiveProposal,
    CognitiveUnsupportedAction,
    ConfidenceEstimate,
    EpistemicItem,
    EpistemicRelation,
    EpistemicStatus,
    EvidenceRef,
    EvidenceSourceType,
    EvidenceItem,
    Hypothesis,
    HypothesisStatus,
    IRUnitReference,
    InvalidationStatus,
    GoalInvariant,
    HaltingDecision,
    HaltingDecisionType,
    NoOpDecision,
    ObjectiveConstraint,
    OutcomeLifecycleState,
    PolicyContext,
    RationaleCode,
    RelationType,
    RiskClass,
    SideEffectClass,
    TaskSpec,
    TaskLifecycleState,
)
from dnc.cognition.canonical import (
    COGNITIVE_SCHEMA_ID,
    COGNITIVE_SCHEMA_VERSION,
    COGNITIVE_STATE_SCHEMA,
    ACTION_OUTCOME_SCHEMA,
    CONFIDENCE_ESTIMATE_SCHEMA,
    EPISTEMIC_RELATION_SCHEMA,
    EPISTEMIC_ITEM_SCHEMA,
    EVIDENCE_REF_SCHEMA,
    HYPOTHESIS_SCHEMA,
    RATIONALE_CODE_SCHEMA,
    TASK_SPEC_SCHEMA,
    ambiguous_task_fields,
    canonical_hash,
    canonical_json,
    task_fingerprint,
)
from dnc.cognition.controller import (
    CognitiveAuthorizationKernel,
    ReferenceCognitiveController,
)
from dnc.cognition.migration import export_cognitive_state, import_cognitive_state, redacted_export
from dnc.cognition.state import (
    CognitiveState,
    validate_action_transition,
    validate_hypothesis_transition,
    validate_outcome_transition,
    validate_task_transition,
)

__all__ = [
    "ActionLifecycleState",
    "ActionOutcome",
    "ACTION_OUTCOME_SCHEMA",
    "COGNITIVE_SCHEMA_ID",
    "COGNITIVE_SCHEMA_VERSION",
    "CapabilityBroker",
    "CapabilityCard",
    "CapabilityRequirement",
    "CapabilitySelection",
    "CapabilityRegistry",
    "CalibrationProfile",
    "CalibrationRegistry",
    "ClarificationRequest",
    "ClarificationStatus",
    "CognitiveBudgets",
    "CognitiveAuthorizationKernel",
    "CognitiveActionType",
    "CognitiveDecision",
    "CognitiveProposal",
    "CognitiveUnsupportedAction",
    "CognitiveState",
    "COGNITIVE_STATE_SCHEMA",
    "ConfidenceEstimate",
    "CONFIDENCE_ESTIMATE_SCHEMA",
    "EPISTEMIC_ITEM_SCHEMA",
    "EPISTEMIC_RELATION_SCHEMA",
    "EpistemicItem",
    "EpistemicRelation",
    "EpistemicStatus",
    "EvidenceRef",
    "EvidenceSourceType",
    "EvidenceItem",
    "EVIDENCE_REF_SCHEMA",
    "GoalInvariant",
    "HaltingDecision",
    "HaltingDecisionType",
    "Hypothesis",
    "HypothesisStatus",
    "HYPOTHESIS_SCHEMA",
    "IRUnitReference",
    "InvalidationStatus",
    "NoOpDecision",
    "ObjectiveConstraint",
    "OutcomeLifecycleState",
    "PolicyContext",
    "RationaleCode",
    "RATIONALE_CODE_SCHEMA",
    "ReferenceCognitiveController",
    "RelationType",
    "RiskClass",
    "SideEffectClass",
    "TASK_SPEC_SCHEMA",
    "TaskSpec",
    "TaskLifecycleState",
    "ambiguous_task_fields",
    "canonical_hash",
    "canonical_json",
    "default_reference_calibration",
    "export_cognitive_state",
    "import_cognitive_state",
    "redacted_export",
    "task_fingerprint",
    "validate_action_transition",
    "validate_hypothesis_transition",
    "validate_outcome_transition",
    "validate_task_transition",
]


def __getattr__(name: str):
    if name in {
        "CapabilityBroker",
        "CapabilityCard",
        "CapabilityRegistry",
        "CapabilityRequirement",
        "CapabilitySelection",
    }:
        from dnc import capabilities

        return getattr(capabilities, name)
    raise AttributeError(name)
